### ISSUE TITLE
Only collects first feature's properties from GeoJSON file

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#127] opened 2015-10-19 17:28 UTC
The `vector_layers.fields` object only contains properties from the first feature in a GeoJSON FeatureCollection, rather than the aggregate of all the properties that might exist in the dataset. For example, the following GeoJSON file: 

``` json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "one": 1
            },
            "geometry": {
                "type": "Point",
                "coordinates": [0, 0]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "two": 2
            },
            "geometry": {
                "type": "Point",
                "coordinates": [1, 1]
            }
        }
    ]
}
```

The expected `vector_layers.fields` object would be:

``` json
{
    "one": "Number",
    "two": "Number"
}
```

But omnivore's output only contains the attribute `one`.  [mapnik-omnivore arrives at this `fields` object](https://github.com/mapbox/mapnik-omnivore/blob/ce7f47af9135acdc144991d5ba27469d76e5649f/lib/geojson.js#L44-L45) by ingesting the geojson file as a mapnik datasource then calling `datasource.describe()`, so I suspect that this is mapnik / node-mapnik issue, but filed here to be sure that we aren't doing something wrong.

cc @scothis @artemp

**Comment by springmeyer** [comment] 2015-11-09 22:21
This behavior is by design in Mapnik:https://github.com/mapnik/mapnik/blob/master/plugins/input/geojson/geojson_datasource.cpp#L318-L319

Will mull on whether it is feasible to fix this with @artemp.

**Comment by rclark** [comment] 2016-01-14 22:06
ping @springmeyer any thoughts here? I can imagine it being somewhat infeasible to actually aggregate a list of all the attributes in a file quickly. However tilelive-omnivore needs to generate complete fields lists as it builds tilejson for these files, so I'm hunting for a good solution.

**Comment by springmeyer** [comment] 2016-01-14 23:36
@rclark taking a closer look at a fix this afternoon. Thanks for the ping.

**Comment by springmeyer** [comment] 2016-01-15 17:52
Per chat with @rclark - best workaround now is to index (using mapnik-index) the GeoJSON files. This will avoid this bug/poor behavior. As far as fixing Mapnik so that even without indexes the full suite of properties are reported, let's track that at https://github.com/mapnik/mapnik/issues/3238

**Comment by springmeyer** [comment] 2016-02-25 15:13
Not actually fixed, re-opening. Follow discussion at https://github.com/mapnik/mapnik/issues/3238

**Comment by springmeyer** [comment] 2016-09-09 22:13
Mapnik issue is now closes as an option is now exposed to ask for more than 5 features: https://github.com/mapnik/mapnik/issues/3238#issuecomment-246055242

**Comment by animaux** [comment] 2016-11-21 15:10
Any news on this? This is still a nagging problem when importing GeoJSON files into Mapbox Studio.

**Comment by who8mycakes** [comment] 2017-01-31 22:12
**Recapping the issue:**
Currently the `new mapnik.Datasource()` step in the Mapnik GeoJSON datasource plugin reads 5 features to assemble properties by default:

`const std::size_t num_features_to_query_ = 5;`

This number is small and limiting since GeoJSON properties vary, and a unique property could occur in features beyond the first 5. I'm going to try resolving this issue by setting `num_features_to_query=<N>` or `num_features_to_query > <N>` where `N` is the number of features.

I will also investigate benchmarking before and after these changes to examine the potential burden of reading more features, and if the overall data processing time is affected. 

WIP PR: https://github.com/mapbox/mapnik-omnivore/pull/162

/cc @springmeyer @GretaCB @artemp @mapsam @flippmoke

**Comment by who8mycakes** [comment] 2017-02-11 01:11
This issued has been resolved by https://github.com/mapbox/mapnik-omnivore/pull/162. Now all features's (up to 1M features) properties will be pulled in from GeoJSON files.

**Closed** 2017-02-13 15:51 UTC
